name: LinuxMirror Caddy Docker Build

on:
  push:
    paths: 'LinuxMirror/**'
  pull_request:
    paths: 'LinuxMirror/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file LinuxMirror/caddy/Dockerfile --tag my-image-name:$(date +%s)
