version: "3.9"
services:
  jmusicbot:
    build: 
      context: jmusicbot-docker
      args:
        TOKEN: $BOT_TOKEN
        OWNER: $BOT_OWNER
        PREFIX: $BOT_PREFIX
    restart: unless-stopped
    environment:
      UID: 1000
      PID: 1000
