name: Build and Push Caddy with Cloudflare module

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get-latest-release.outputs.TAG }}
      image_name: ${{ steps.set-image-name.outputs.IMAGE_NAME }}
    steps:
      - name: Get latest Caddy release tag
        id: get-latest-release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
          clean_tag=${latest_release#v}  # Remove 'v' prefix
          echo "Latest release: $clean_tag"
          echo "TAG=$clean_tag" >> $GITHUB_OUTPUT

      - name: Set image name
        id: set-image-name
        run: |
          name=ghcr.io/${{ github.repository_owner }}/caddy-cloudflare
          name=$(echo $name | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          echo "IMAGE_NAME=$name" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
          - linux/riscv64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{needs.prepare.outputs.image_name}}
          tags: type=semver,pattern={{version}},value=v${{needs.prepare.outputs.latest_tag}}

      - name: Set up QEMU
        if: ${{ matrix.platform != 'linux/amd64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm,arm64,riscv64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: WebServer/docker-caddy-cloudflare
          build-args: CADDY_VERSION=${{needs.prepare.outputs.latest_tag}}
          outputs: type=image,name=${{needs.prepare.outputs.image_name}},push-by-digest=true,name-canonical=true,push=true
  
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  push:
    needs: 
      - prepare
      - build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          name: digests-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{needs.prepare.outputs.image_name}}
          tags: type=semver,pattern={{version}},value=v${{needs.prepare.outputs.latest_tag}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          digest_files=$(ls)
          for digest_file in $digest_files; do
            docker buildx imagetools create -t ${{needs.prepare.outputs.image_name}}:${{needs.prepare.outputs.latest_tag}} ghcr.io/${{ github.repository_owner }}/caddy-cloudflare@sha256:$digest_file
          done

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{needs.prepare.outputs.image_name}}:${{needs.prepare.outputs.latest_tag}}
